services:
  - type: web
    name: ikukyu-simulator
    env: static
    buildCommand: cd /opt/render/project/src && npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 